<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from common library classes
__( 'Cache file %s is not readable.', 'nextgen-facebook' );
__( 'Cache folder %s is not writable.', 'nextgen-facebook' );
__( 'edit', 'nextgen-facebook' );
__( 'Error connecting to %1$s for caching (HTTP code %2$d).', 'nextgen-facebook' );
__( 'Error removing cache file %s.', 'nextgen-facebook' );
__( 'Failed to create the %s cache folder.', 'nextgen-facebook' );
__( 'Failed to open the cache file %s for reading.', 'nextgen-facebook' );
__( 'Failed to open the cache file %s for writing.', 'nextgen-facebook' );
__( 'Forever', 'nextgen-facebook' );
__( 'Notice', 'nextgen-facebook' );
__( 'PHP cURL library is missing &mdash; contact your hosting provider to have the cURL library installed.', 'nextgen-facebook' );
__( 'Please contact your hosting provider to have this setting disabled.', 'nextgen-facebook' );
__( 'Please contact your hosting provider to have this setting disabled or install a newer version of PHP.', 'nextgen-facebook' );
__( 'Reference: %s', 'nextgen-facebook' );
__( 'Requests to cache this URL will be ignored for %d second(s).', 'nextgen-facebook' );
__( '%s Notice', 'nextgen-facebook' );
__( 'The maximum number of URL redirects (%d) may have been exceeded.', 'nextgen-facebook' );
__( 'The PHP "%s" setting is enabled &mdash; the PHP cURL library cannot follow URL redirects.', 'nextgen-facebook' );
__( 'The "%s" setting is deprecated since PHP version 5.3 and removed from PHP since version 5.4.', 'nextgen-facebook' );
__( 'This notice can be dismissed for %s.', 'nextgen-facebook' );
__( 'This notice can be dismissed permanently.', 'nextgen-facebook' );
_x( 'error', 'notification type', 'nextgen-facebook' );
_x( 'warning', 'notification type', 'nextgen-facebook' );
