<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-container',
) );

do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup( array(
	'close'   => '</body>',
	'context' => 'body',
) );
?>
<script type="text/javascript">
	
	jQuery(document).ready(function(){
		jQuery('body.page').removeClass('sticky');
		var lastScrollTop = 0;
		jQuery(window).scroll(function(event){
		   var st = jQuery(this).scrollTop();
		   

		   if (st == 0) {
		   	jQuery('body.page').removeClass('sticky');
		   }
		   else if (st > lastScrollTop){
		      jQuery('body.page').addClass('sticky');
		   } 
		   lastScrollTop = st;
		});
});
</script>
</html>
