<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// Initialize Genesis.
genesis();
?>
<?php /* Template Name: mainhomepage */ ?>
<div class="tp-bgimg defaultimg " style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;http://dhruphost.com/wordpress/dhfeb2017_043/wp-content/uploads/2017/02/02-1.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="http://dhruphost.com/wordpress/dhfeb2017_043/wp-content/uploads/2017/02/02-1.png"></div>


 
<?php 
//global $wp;
$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
// get current url with query string.
//$current_url =  home_url( $wp->request );
//print_r($url);

if (strpos($url , "category") == false && !is_archive())
{
 ?>
 <?php include (TEMPLATEPATH . '/header.php'); ?>
<div id="midbox">
<div id="mainhome">
<a name="maincontent" id="maincontent"></a>
<div class="blogpostwrapper">
<?php if (have_posts()) : ?>
<?php while (have_posts()) : the_post(); ?>
<div class="blogpost">
<?php

  echo '<a href="' . get_permalink( $_post->ID ) . '" title="' . esc_attr( $_post->post_title ) . '">';
        echo get_the_post_thumbnail( $_post->ID, 'thumbnail' );
        echo '</a>';
?>
<h3 class="entrytitle" id="post-<?php the_ID(); ?>"> <a href="<?php the_permalink() ?>" rel="bookmark"><?php the_title(); ?> </a> </h3>


<?php the_content(); ?>



</div>
<?php endwhile; ?>
<?php else : ?>
<h6 class="center">Not Found</h6>
<p class="center">Sorry, but you are looking for something that isn't here.</p>
<?php include (TEMPLATEPATH . "/searchform.php"); ?>
<?php endif; ?>
</div>
<!-- End WordPress Loop -->
</div>
<!-- end main content area -->
</div>
<!-- end middle content area -->
<!-- Footer -->

<?php include (TEMPLATEPATH . '/footer.php'); ?>
<?php 
}
 ?>

